<#
.SYNOPSIS
    Next.js TypeScript Deployment Script for Windows Server (7-Zip & PM2).

.PARAMETER ReleaseId
    Unique release timestamp generated by the CI workflow.

.PARAMETER SourceDir
    The GitHub Actions runner workspace root directory.

.PARAMETER AppName
    The application process name defined in ecosystem.config.js.
#>

param (
    [Parameter(Mandatory=$true)]
    [string]$ReleaseId,

    [Parameter(Mandatory=$false)]
    [string]$SourceDir = $env:GITHUB_WORKSPACE,

    [Parameter(Mandatory=$false)]
    [string]$AppName = "helpdesk-embedded"
)

# Stop execution immediately if any command encounters an error
$ErrorActionPreference = "Stop"

# ==============================================================================
# BLOCK 1: PATH DEFINITIONS & 7-ZIP DETECTION
# ==============================================================================
$AppRootDir     = "C:\helpdesk-embedded"                      # App root directory on Windows host
$ReleasesDir    = "$AppRootDir\releases"                  # Parent releases folder
$NewReleaseDir  = "$ReleasesDir\release-$ReleaseId"       # Destination path for this release
$JunctionLink   = "$AppRootDir\current"                   # Active junction link consumed by PM2
$EcosystemFile  = "$AppRootDir\ecosystem.config.js"       # PM2 ecosystem configuration path
$ZipFile        = "$SourceDir\release-$ReleaseId.zip"     # Temporary deployment archive

Write-Host "==================================================" -ForegroundColor Cyan
Write-Host " Starting Fast 7-Zip Deployment: Release $ReleaseId" -ForegroundColor Cyan
Write-Host "==================================================" -ForegroundColor Cyan

# Resolve 7-Zip executable path
$7zExe = Get-Command "7z" -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Source
if (-not $7zExe) {
    $7zExe = "C:\Program Files\7-Zip\7z.exe"
}

if (-not (Test-Path $7zExe)) {
    throw "Fatal Error: 7-Zip executable not found at '$7zExe'. Please install 7-Zip or add it to system PATH."
}

# Ensure master releases directory exists
if (-not (Test-Path $ReleasesDir)) {
    Write-Host "[1/6] Creating master releases folder..." -ForegroundColor Yellow
    New-Item -ItemType Directory -Path $ReleasesDir -Force | Out-Null
}

New-Item -ItemType Directory -Path $NewReleaseDir -Force | Out-Null

# ==============================================================================
# BLOCK 2: BUNDLE ARTIFACTS WITH 7-ZIP
# ==============================================================================
Write-Host "[2/6] Archiving build artifacts and node_modules with 7-Zip..." -ForegroundColor Green
Push-Location -Path $SourceDir

try {
    # Include TypeScript Next.js artifacts
    $TargetsToZip = @(".next", "node_modules", "package.json", "package-lock.json")
    
    if (Test-Path "public") { $TargetsToZip += "public" }
    if (Test-Path "next.config.ts") { $TargetsToZip += "next.config.ts" }

    # Fast compression mode (-mx=1)
    & $7zExe a -tzip -mx=1 "$ZipFile" $TargetsToZip -y | Out-Null

    if ($LASTEXITCODE -ne 0) {
        throw "7-Zip failed to create archive '$ZipFile' with exit code $LASTEXITCODE"
    }
}
finally {
    Pop-Location
}

# ==============================================================================
# BLOCK 3: EXTRACT ARCHIVE TO RELEASE DIRECTORY
# ==============================================================================
Write-Host "[3/6] Extracting release bundle into $NewReleaseDir..." -ForegroundColor Green

& $7zExe x "$ZipFile" "-o$NewReleaseDir" -y | Out-Null

if ($LASTEXITCODE -ne 0) {
    throw "7-Zip failed to extract archive into '$NewReleaseDir' with exit code $LASTEXITCODE"
}

# Remove temporary zip archive
Remove-Item "$ZipFile" -Force -ErrorAction SilentlyContinue

# Update ecosystem.config.js in root directory if modified in source code
if (Test-Path "$SourceDir\ecosystem.config.js") {
    Write-Host "[3/6] Updating root ecosystem.config.js..." -ForegroundColor Yellow
    Copy-Item "$SourceDir\ecosystem.config.js" $EcosystemFile -Force
}

# ==============================================================================
# BLOCK 4: ATOMIC WINDOWS JUNCTION SWAP
# ==============================================================================
Write-Host "[4/6] Swapping Windows Junction Link ($JunctionLink -> $NewReleaseDir)..." -ForegroundColor Green

if (Test-Path $JunctionLink) {
    cmd /c rmdir "$JunctionLink"
}

cmd /c mklink /J "$JunctionLink" "$NewReleaseDir"

# ==============================================================================
# BLOCK 5: PM2 ZERO-DOWNTIME RELOAD
# ==============================================================================
Write-Host "[5/6] Executing PM2 reload for app '$AppName'..." -ForegroundColor Green

Set-Location -Path $AppRootDir

# Reload cluster mode app with updated environment settings
pm2 reload ecosystem.config.js --only $AppName --update-env

# ==============================================================================
# BLOCK 6: RELEASE RETENTION CLEANUP
# ==============================================================================
Write-Host "[6/6] Enforcing release retention policy (Keeping 5 newest)..." -ForegroundColor Green

$OldReleases = Get-ChildItem -Path $ReleasesDir -Directory | 
    Sort-Object CreationTime -Descending | 
    Select-Object -Skip 5

foreach ($OldRelease in $OldReleases) {
    Write-Host " -> Removing old release folder: $($OldRelease.FullName)" -ForegroundColor DarkGray
    Remove-Item $OldRelease.FullName -Recurse -Force
}

Write-Host "==================================================" -ForegroundColor Cyan
Write-Host " Deployment Completed Successfully! Release $ReleaseId is LIVE." -ForegroundColor Cyan
Write-Host "==================================================" -ForegroundColor Cyan